version: '3.3'

services:
  # PostgreSQL Database
  ai_fitness_planner_db:
    image: postgres:15-alpine
    container_name: ai_fitness_planner_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "4553:5432"
    volumes:
      - db_data_ai_fitness_planner:/var/lib/postgresql/data
    networks:
      - ai-fitness-network
      - sp-net
  
# MongoDB Database for USDA Nutrition Data
  mongodb_ai_fitness_planner:
    image: mongo:7.0
    container_name: mongodb_ai_fitness_planner
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27019:27017"  # Different port to avoid conflicts
    volumes:
      - mongodb_data_ai_fitness_planner:/data/db
      - ./data/mongodb_init:/docker-entrypoint-initdb.d  # For init scripts
    networks:
      - ai-fitness-network
      - sp-net

  # FastAPI Backend
  fast_api_ai_fitness_planner:
    restart: always
    build: 
      context: ./fast_api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=ai-fitness-planner
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    volumes:
      - ./:/app
    ports:
      - "1015:8000"
    command: ["--host", "0.0.0.0", "fast_api.app.main:app", "--reload"]
    networks:  # ADD THIS SECTION
      - ai-fitness-network
      - sp-net
    depends_on:
      - ai_fitness_planner_db
      - mongodb_ai_fitness_planner

  # Streamlit Frontend
  streamlit_app_ai_fitness_planner:
    build: 
      context: ./streamlit
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: "streamlit run streamlit/🏠_home.py"
    ports:
      - "8526:8501"
    volumes:
      - ./streamlit:/usr/src/app
    networks:
      - ai-fitness-network
      - sp-net
    depends_on:
      - ai_fitness_planner_db
      - mongodb_ai_fitness_planner

# Named volumes for data persistence
volumes:
  db_data_ai_fitness_planner:
    driver: local
  mongodb_data_ai_fitness_planner:
    driver: local

# Networks
networks:
  ai-fitness-network:
    driver: bridge
  sp-net:
    external: true