import streamlit as st
from datetime import datetime

def render_footer():
    """Render the application footer with attribution and disclaimers"""
    
    # Add some spacing
    st.markdown("---")
    
    # Disclaimer section
    st.markdown(
        """
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; margin-top: 2rem;">
            <div style="text-align: center; margin-bottom: 15px;">
                <h4 style="color: #495057; margin-bottom: 10px;">⚠️ Important Disclaimer</h4>
                <p style="color: #6c757d; font-size: 14px; line-height: 1.6; margin-bottom: 0;">
                    <strong>For Demonstration Purposes Only</strong><br>
                    This application is created for educational and demonstration purposes only. 
                    The meal plans, nutrition advice, and workout recommendations generated by this system 
                    are <strong>not intended as medical or professional health advice</strong>.
                    <br><br>
                    <strong>Please consult with qualified healthcare professionals, registered dietitians, 
                    or certified fitness trainers before starting any new diet or exercise program.</strong>
                    Individual results may vary, and this tool should not replace professional medical guidance.
                </p>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    
    # Attribution section (separate markdown call)
    st.markdown(
        """
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px; margin-top: 10px;">
            <hr style="margin: 20px 0; border-color: #dee2e6;">
            <div style="text-align: center;">
                <p style="color: #495057; margin-bottom: 10px; font-size: 16px;">
                    🚀 <strong>Built by Josh Janzen</strong> 
                </p>
                <p style="color: #6c757d; font-size: 14px; margin-bottom: 10px;">
                    AI Fitness Planner - Demonstrating LangChain Agents & Modern AI Architecture
                </p>
                <p style="color: #6c757d; font-size: 12px; margin-bottom: 0;">
                    Powered by: FastAPI • MongoDB • LangChain • OpenAI • Streamlit<br>
                    © {year} Josh Janzen. Demo application - not for commercial use.
                </p>
            </div>
        </div>
        """.format(year=datetime.now().year),
        unsafe_allow_html=True,
    )