import streamlit as st


def render_sidebar_disclaimer():
    """Render the disclaimer in the sidebar as an expander, default closed"""

    with st.sidebar:
        with st.expander("⚠️ Important Disclaimer", expanded=False):
            st.markdown(
                """
                **For Demonstration Purposes Only**
                
                This application is created for educational and demonstration purposes only. 
                The meal plans, nutrition advice, and workout recommendations generated by this system 
                are **not intended as medical or professional health advice**.
                
                **Please consult with qualified healthcare professionals, registered dietitians, 
                or certified fitness trainers before starting any new diet or exercise program.** 
                Individual results may vary, and this tool should not replace professional medical guidance.
                """,
                help="This disclaimer applies to all content generated by this application.",
            )
